---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: newrelic-repo
  namespace: newrelic
spec:
  interval: 1m0s
  url: https://helm-charts.newrelic.com

---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: newrelic-minions
  namespace: newrelic
spec:
  interval: 5m
  chart:
    spec:
      chart: synthetics-minion
      version: "1.0.31"
      sourceRef:
        kind: HelmRepository
        name: newrelic-repo
        namespace: newrelic
      interval: 10m
  values:
    synthetics:
      privateLocationKey: NRSP-us01D670440EA1EB517637D6BB0BE634325
