apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kibana-secret-setting
  namespace: elastic
spec:
  encryptedData:
    xpack.security.encryptionKey: AgC6gSDWbCkVOHhmDmtn/jXQ488NBWlrbWiWLGjirtcUF8I0/q9fyHt3cDD8qRMbQOp+p9dC8k6A7eNVPgtxNCzuUXMxst3mQkDPRmTVGV+p6P8BqXr53gRukuVAmGz9lNIFrYWPHyxsmF/rAoJf4NNngI9CQasGzvMLKJeCrJeRxCdsTAYriUc39xsRpVWR3H/BhlsivxgsCNwK+8w+cD6ac3qj6iLgR3xwswbqlt8AtDfW/sU5Ypd9LsNMR+3+ip5BmyQaGyD+TgU0+fHPn8cWDFfEPM//+tf4I/xj2RiZe5TD7V0SefI9B1LWHgGt+OKU8AuKteC32Xb5NKiOervX1kRUbfZZgMj05ZlG5GWg3NB8CNBi9gKQSrV3qXocOl28fCnPJ3OUa+CFvLVNbctuCbPeP9mRe8opyy1Hrp2mEB5OePgMfdpBfw+9wLc8Q44b2LbJFcDtFhJvGJVGrDKwn2bagj11TfSenbHZQ/hW/ZwPVim5F/Yk9IRmTES8XJLWhjmOT7p8QY9sMkfJncdkmrRCjtBO8jHjDDkcsbJ/dyJIyIdPx3RGln6UvqSy59a4LB1hY61ivgVNj8Jj00wyUwIoKYnwAK8kzHvinGWDk69oICS822Bk11dRrGAr8Ue6Dk9rYF/GLt81qd8DEPFZBcxnyECKHu88BbDCgodvtxpbTeUknLT8XVRrIg4ZMdW1+0KT/w8wnZIHFkVlAJROgTSK5HgGjQTcgjjafbd2PX68PhAvsuslZl9nmPf5MqTXmvg4OsPvf05aer4FOlUi
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: kibana-secret-setting
      namespace: elastic

