apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysecret
  namespace: flux-system
spec:
  encryptedData:
    foo: AgC9ye01AFdP9Q0X0KXDIG8n7ouq/au6DD1P1aaY6TYaqIUNsg7JfkVuKnLVqsqGOlLqBTTHoyJixc6w97TZzUv3os/B8qmGS5stGaikygucCqttrnqa1960d8XbUAZ4BV808er36UVdl2sffav+MsWSlLF0hBsdUHegBQ/5Wvy7wCbZTcVxrbq1njAtPH650gpFoJWzHKv6B5XJJlHDvPgzjSrDPOOHE+xpmxOQtyW0CeHrGYtVSiQIPeTTJLKDfzXUXuL2VMjjLHHUH2/Vn36W70J+VFowU+6yVZ0kZBWB377BQl2W599zVbbzk4Kge71DK+F89aTX2NB02JPjmEYWHl+I+4z5qLBaQnBUasYFx5AIvu5fMnAmAfPVjM6C4vloX24SVpzxAe6OoBxzCc5UWxPscQx7pKv3mR7Ud0KmVT3juWBPItTmvtgheFtjggzry3lKGwCzBzfte0VzASPT/SbLcUNE4stsLJRsoGNiShu4+BsfZdKowp2ZUOMfm7EcxvWUftQ4tgDq6zjF4H6gg6yyYQrXcLU41USsztb99lDnWGdrFRL4Yiz+yUso4L9daE7QgY9uDwtWXKsUhbEwWL7csCScA5qOWp7J9uUZu2dcdKb8N9O2J7v2ahgM3naaUHHz/5RvhD9t+poOSu5gxTT1N/B/We2/1wflnfZErEKP+mNEPkZVLllfK5iWlGbUmuWgDNVD5ONmBGTdgEX/f8iv9UHPT3nE4ftMIC09uohq6gcvkjDa9zbZYAjY0OaCMUrsh8xIuDsB1q0EoVSeaA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysecret
      namespace: flux-system

