apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: elk-kibana
spec:
  version: 7.12.1
  count: 2
  elasticsearchRef:
    name: "elastic"
  podTemplate:
    spec:
      containers:
      - name: kibana
        env:
          - name: NODE_OPTIONS
            value: "--max-old-space-size=1024"
        resources:
          requests:
            memory: 1Gi
            cpu: 0.5
          limits:
            memory: 2.5Gi
            cpu: 2
      config:
        elasticsearch.requestHeadersWhitelist:
        - authorization
  secureSettings:
  - secretName: kibana-secret-settings
  http:
    service:
      spec:
        type: LoadBalancer # default is ClusterIP
    tls:
      selfSignedCertificate:
        subjectAltNames:
        - dns: kibana.local